### ISSUE TITLE
FileObserver implementation

### ISSUE THREAD

**Issue by ebarriosjr** [hamxabaig/ama#1]
Hi, I saw in a post on the itinance/react-native-fs that you have an implementation of fileObserver working with react native. I am trying to implement this myself and thought maybe you can share the way you did it? 
Thanks!

**Comment by hamxabaig** [comment]
@ebarriosjr hey, I'll try to find it but it was a long time ago and its probably in my old macbook. But let me see if i have it in cloud somewhere. I'll get back to you :)

**Comment by hamxabaig** [comment]
I found it, but realized its only for Android because at that time iOS did'nt have any API like that i think (4 years ago, not sure if it still does)

[Here is the link](https://gist.github.com/hamxabaig/15e5c64c59aed2abae34f7b244a309c2)

All it does is keep listening for file changes (new files) and then sync them.

**Comment by ebarriosjr** [comment]
Amazing! Thank you very much!
